### ISSUE TITLE
Info on flashing

### ISSUE THREAD

**Issue by tuimz** [Sergey-SRG/ESPHome-Xiaomi-Philips-light#2]
How do you flash the downlights? Is there an OTA way to flash from miio to esphome?

**Comment by Sergey-SRG** [comment]
> How do you flash the downlights? 

Flash like a regular ESP8266.

![photo_2020-11-08_19-29-34](https://user-images.githubusercontent.com/3891900/98470749-e73be400-21f8-11eb-871e-d11ab848e46f.jpg)
![photo_2020-11-08_19-29-38](https://user-images.githubusercontent.com/3891900/98470750-e86d1100-21f8-11eb-9830-d38e4cf3ff13.jpg)
![photo_2020-11-08_19-29-43](https://user-images.githubusercontent.com/3891900/98470751-e905a780-21f8-11eb-8071-4ffb75c07c1f.jpg)

> Is there an OTA way to flash from miio to esphome?

At the moment, I don't know of any way to update the firmware on ESPHome via OTA.

P.S. If such a method appears, I will definitely report it in this repository.

**Comment by tuimz** [comment]
That is unfortunate. I have 9 of them but they are already build into the ceiling :(

**Comment by sdesalve** [comment]
> At the moment, I don't know of any way to update the firmware on ESPHome via OTA.

Hi, is there any way to OTA install ESPHome? I own 25 Zhirui that are already mounted on the ceiling...
