### ISSUE TITLE
Instructions how-to

### ISSUE THREAD

**Issue by Verguldebarman** [Sergey-SRG/ESPHome-Xiaomi-Philips-light#3]
Really interested to get Xiaomi Philips light bulbs to work with Home Assistant. Would it be possible to write a howto ?

**Comment by syssi** [comment]
Take a look at this issue for additional details: https://github.com/arendst/Tasmota/issues/3055

A short summary:

1. Remove the dome. The dome is glued to the base. Use a knife and some tension.
2. Uncover the pads. 
3. Attach a Serial-to-USB Adapter. (GPIO0, GPIO15, VCC, RXD, TXD, GND)
    cp. https://user-images.githubusercontent.com/10838968/50249596-c25cde80-03de-11e9-8b13-5e75c992e08b.jpg
4. Flash the `xiaomi_light.yaml` to your device.
5. Remove the wires, attach the dome and use the device.

![philipslight-without-dome](https://user-images.githubusercontent.com/2735933/103169215-1c000b00-483a-11eb-9ef8-0e3684fa81f4.jpg)
![philipslight-ftdi-attached](https://user-images.githubusercontent.com/2735933/103169213-19051a80-483a-11eb-8cc1-510d4a4e7da4.jpg)
